import { Type, Heading, List, Link, Code, AlertTriangle, Gamepad2, AtSign, Layout } from "lucide-react"

export const HELP_SECTIONS = [
  { id: "text", icon: Type },
  { id: "headings", icon: Heading },
  { id: "lists", icon: List },
  { id: "links", icon: Link },
  { id: "blocks", icon: Code },
  { id: "alerts", icon: AlertTriangle },
  { id: "games", icon: Gamepad2 },
  { id: "social", icon: AtSign },
  { id: "layout", icon: Layout },
]

export const HELP_FEATURES = [
  { id: "bold", section: "text", syntax: "**texto**" },
  { id: "italic", section: "text", syntax: "*texto*" },
  { id: "strikethrough", section: "text", syntax: "~~texto~~" },
  { id: "inlineCode", section: "text", syntax: "`código`" },
  { id: "headings", section: "headings", syntax: "# a ######" },
  { id: "unorderedList", section: "lists", syntax: "- item" },
  { id: "orderedList", section: "lists", syntax: "1. item" },
  { id: "checklist", section: "lists", syntax: "- [ ] / - [x]" },
  { id: "link", section: "links", syntax: "[texto](url)" },
  { id: "image", section: "links", syntax: "![alt](url)" },
  { id: "imageCustom", section: "links", syntax: '<img src="..." width="..." />' },
  { id: "youtube", section: "links", syntax: "URL do YouTube" },
  { id: "codeBlock", section: "blocks", syntax: "```código```" },
  { id: "blockquote", section: "blocks", syntax: "> texto" },
  { id: "hr", section: "blocks", syntax: "---" },
  { id: "table", section: "blocks", syntax: "| Col | Col |" },
  { id: "alertInfo", section: "alerts", syntax: ":::info" },
  { id: "alertNote", section: "alerts", syntax: ":::note" },
  { id: "alertTip", section: "alerts", syntax: ":::tip" },
  { id: "alertImportant", section: "alerts", syntax: ":::important" },
  { id: "alertWarning", section: "alerts", syntax: ":::warning" },
  { id: "alertDanger", section: "alerts", syntax: ":::danger" },
  { id: "alertSuccess", section: "alerts", syntax: ":::success" },
  { id: "alertQuestion", section: "alerts", syntax: ":::question" },
  { id: "alertExample", section: "alerts", syntax: ":::example" },
  { id: "alertBug", section: "alerts", syntax: ":::bug" },
  { id: "alertNeutral", section: "alerts", syntax: ":::neutral" },
  { id: "gameCard", section: "games", syntax: "!game(slug)" },
  { id: "gameMini", section: "games", syntax: "!game:mini(slug)" },
  { id: "gameGrid", section: "games", syntax: "!game:grid(slug1, slug2+, ...)" },
  { id: "gameGridAuto", section: "games", syntax: "!game:grid-auto(slug1, slug2+, ...)" },
  { id: "mention", section: "social", syntax: "@usuario" },
  { id: "spoiler", section: "social", syntax: "||texto||" },
  { id: "spoilerImg", section: "social", syntax: "<spoilerimg />" },
  { id: "center", section: "layout", syntax: "<center>...</center>" },
  { id: "desktop", section: "layout", syntax: "<desktop>...</desktop>" },
  { id: "mobile", section: "layout", syntax: "<mobile>...</mobile>" },
]
