import { Type, Heading, List, Link, Code, AlertTriangle, Gamepad2, AtSign, Layout } from "lucide-react"

export const HELP_SECTIONS = [
  { id: "text", icon: Type },
  { id: "headings", icon: Heading },
  { id: "lists", icon: List },
  { id: "links", icon: Link },
  { id: "blocks", icon: Code },
  { id: "alerts", icon: AlertTriangle },
  { id: "games", icon: Gamepad2 },
  { id: "social", icon: AtSign },
  { id: "layout", icon: Layout },
]

export const HELP_FEATURES = [
  { section: "text", syntax: "**texto**", description: "Texto em negrito.", example: "**isso fica em negrito**", preview: "**isso fica em negrito**" },
  { section: "text", syntax: "*texto*", description: "Texto em itálico.", example: "*isso fica em itálico*", preview: "*isso fica em itálico*" },
  { section: "text", syntax: "~~texto~~", description: "Texto riscado (tachado).", example: "~~texto riscado~~", preview: "~~texto riscado~~" },
  { section: "text", syntax: "`código`", description: "Código inline.", example: "`console.log('oi')`", preview: "`console.log('oi')`" },
  { section: "headings", syntax: "# a ######", description: "Títulos de H1 (maior) até H6 (menor). Quanto mais #, menor o título.", example: "# Título Grande\n## Subtítulo\n### Menor ainda" },
  { section: "lists", syntax: "- item", description: "Lista não ordenada (com bolinhas).", example: "- Primeiro item\n- Segundo item\n- Terceiro item", preview: "- Primeiro\n- Segundo\n- Terceiro" },
  { section: "lists", syntax: "1. item", description: "Lista ordenada (numerada).", example: "1. Primeiro\n2. Segundo\n3. Terceiro", preview: "1. Primeiro\n2. Segundo\n3. Terceiro" },
  { section: "lists", syntax: "- [ ] / - [x]", description: "Checklist com itens marcáveis.", example: "- [ ] Pendente\n- [x] Concluído", preview: "- [ ] Pendente\n- [x] Concluído" },
  { section: "links", syntax: "[texto](url)", description: "Cria um link clicável.", example: "[Clique aqui](https://exemplo.com)", preview: "[Clique aqui](https://exemplo.com)" },
  { section: "links", syntax: "![alt](url)", description: "Insere uma imagem.", example: "![Logo](https://exemplo.com/img.png)" },
  { section: "links", syntax: '<img src="..." width="..." />', description: "Imagem com tamanho customizado.", example: '<img src="https://exemplo.com/img.png" alt="desc" width="400" />' },
  { section: "links", syntax: "URL do YouTube", description: "Cole um link do YouTube e ele vira um player automaticamente.", example: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
  { section: "blocks", syntax: "```código```", description: "Bloco de código com múltiplas linhas.", example: "```\nfunction oi() {\n  return 'olá'\n}\n```" },
  { section: "blocks", syntax: "> texto", description: "Citação / blockquote.", example: "> Isso é uma citação", preview: "> Isso é uma citação" },
  { section: "blocks", syntax: "---", description: "Linha horizontal separadora.", preview: "---" },
  { section: "blocks", syntax: "| Col | Col |", description: "Tabela com colunas e linhas.", example: "| Nome | Nota |\n| --- | --- |\n| Jogo A | 10 |", preview: "| Nome | Nota |\n| --- | --- |\n| Jogo A | 10 |" },
  { section: "alerts", syntax: ":::info", description: "Bloco informativo neutro.", example: ":::info\nInformação importante\n:::" },
  { section: "alerts", syntax: ":::note", description: "Nota complementar ou observação.", example: ":::note\nIsso é apenas uma nota.\n:::" },
  { section: "alerts", syntax: ":::tip", description: "Dica útil para o leitor.", example: ":::tip\nUse arma de gelo contra inimigos de fogo.\n:::" },
  { section: "alerts", syntax: ":::important", description: "Informação importante que merece destaque.", example: ":::important\nIsso é muito relevante.\n:::" },
  { section: "alerts", syntax: ":::warning", description: "Aviso importante.", example: ":::warning\nCuidado com esta área.\n:::" },
  { section: "alerts", syntax: ":::danger", description: "Alerta crítico ou perigoso.", example: ":::danger\nEssa escolha é irreversível.\n:::" },
  { section: "alerts", syntax: ":::success", description: "Mensagem de sucesso ou conclusão.", example: ":::success\nMissão concluída!\n:::" },
  { section: "alerts", syntax: ":::question", description: "Pergunta ou reflexão destacada.", example: ":::question\nVocê já tentou essa abordagem?\n:::" },
  { section: "alerts", syntax: ":::example", description: "Exemplo prático ou demonstração.", example: ":::example\nVeja este caso aplicado.\n:::" },
  { section: "alerts", syntax: ":::bug", description: "Problema conhecido ou comportamento inesperado.", example: ":::bug\nExiste um erro nessa versão.\n:::" },
  { section: "alerts", syntax: ":::neutral", description: "Observação neutra sem ênfase emocional.", example: ":::neutral\nApenas uma observação geral.\n:::" },
  { section: "games", syntax: "!game(slug)", description: "Exibe um card detalhado de um jogo. O slug pode ser encontrado na URL da página do jogo.", example: "!game(the-last-of-us)" },
  { section: "games", syntax: "!game:mini(slug)", description: "Versão compacta do card de jogo, ideal para listas.", example: "!game:mini(celeste)" },
  { section: "games", syntax: "!game:grid(slug1, slug2+, ...)", description: "Vitrine de jogos em carrossel manual. Adicione + no final do slug para destacar como favorito.", example: "!game:grid(celeste, hollow-knight+)" },
  { section: "games", syntax: "!game:grid-auto(slug1, slug2+, ...)", description: "Vitrine de jogos com carrossel automático infinito. Também suporta + para favoritos.", example: "!game:grid-auto(celeste, hollow-knight+, hades)" },
  { section: "social", syntax: "@usuario", description: "Menciona um usuário. Digite @ para ver sugestões de pessoas que você segue.", example: "@username" },
  { section: "social", syntax: "||texto||", description: "Esconde o texto como spoiler. O usuário precisa clicar para revelar.", example: "O assassino é ||o mordomo||" },
  { section: "social", syntax: "<spoilerimg />", description: "Insere uma imagem com desfoque de spoiler.", example: '<spoilerimg src="https://exemplo.com/img.png" alt="desc" width="400" />' },
  { section: "layout", syntax: "<center>...</center>", description: "Centraliza o conteúdo (texto ou imagens).", example: "<center>Texto centralizado</center>", preview: "<center>Texto centralizado</center>" },
  { section: "layout", syntax: "<desktop>...</desktop>", description: "Conteúdo visível apenas no desktop.", example: "<desktop>\nIsso só aparece no PC\n</desktop>" },
  { section: "layout", syntax: "<mobile>...</mobile>", description: "Conteúdo visível apenas no celular.", example: "<mobile>\nIsso só aparece no celular\n</mobile>" },
]
